[tool.black]
line-length = 88 

[tool.ruff]
line-length = 88 
ignore = ["E501"]
exclude = ["docs/", "scripts/", "tests/"]
select = ["F", "E", "W", "I001"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]