# where find models to test
models_path: 'where/to/find/models'

# where to save the resulting plots
output_path: 'where/to/save/outputs'

# these ranges will be used when generating predictions using the routee-powertrain models
feature_ranges:
  speed:
    max: 160
    min: 0
    steps: 80

  grade:
    max: 20
    min: -20
    steps: 40

  road_priority:
    max: 7
    min: 0
    steps: 8

  entry_angle:
    max: 180
    min: -180
    steps: 36

  exit_angle:
    max: 180
    min: -180
    steps: 36

