# where find models to test
models_path: 'where/to/find/models'

# where to save the resulting plots
output_path: 'where/to/save/outputs'

# number of links generated for the test
num_links: 15

# features to be iterated using integers instead of floats
int_features:
  - road_priority

# these ranges will be used when generating predictions using the routee-powertrain models
feature_ranges:
  speed:
    max: 160
    min: 0
    default: 65

  grade:
    max: 15
    min: -15
    default: 0

  road_priority:
    max: 8
    min: 0
    default: 0

  entry_angle:
    max: 180
    min: -180
    default: 0

  exit_angle:
    max: 180
    min: -180
    default: 0

  ratio_ffs:
    max: 2
    min: 0
    default: 1
